<a href="https://colab.research.google.com/github/Leonardogamu/mcd---aprendizaje_automatico_2025/blob/main/Tarea_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tarea 2**
## ○ Elegir un conjunto de datos y definirlo

El siguiente conjunto de datos a utilizar, es un dataset que recopila distinta informacion sobre habitos y estilo de vida de las personas, como por ejemplo higiene del sueño, edad, niveles de colesterol, su numero de pasos diarios, indice de masa corporal, entre otros registros por persona.

Con esa informacion podremos generar varios analisis para estudiar el comportamiento y la repercusion del mismo, en las personas a estudiar.

###El dataset lo obtuve de Kaggle:

https://www.kaggle.com/datasets/chik0di/health-and-lifestyle-dataset

--------------------------------------------------------------------------

## ○ Cargar conjunto de datos mediante pandas

In [2]:
import pandas as pd

In [30]:
data=pd.read_csv('/content/health_lifestyle_dataset.csv')
data

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
0,1,56,Male,20.5,4198,3.9,3.4,1602,0,0,97,161,111,240,0,0
1,2,69,Female,33.3,14359,9.0,4.7,2346,0,1,68,116,65,207,0,0
2,3,46,Male,31.6,1817,6.6,4.2,1643,0,1,90,123,99,296,0,0
3,4,32,Female,38.2,15772,3.6,2.0,2460,0,0,71,165,95,175,0,0
4,5,60,Female,33.6,6037,3.8,4.0,3756,0,1,98,139,61,294,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,53,Male,33.1,4726,3.9,2.0,3118,0,1,56,105,76,282,0,0
99996,99997,22,Male,35.1,11554,4.5,3.1,1967,0,0,51,149,77,192,0,0
99997,99998,37,Male,18.9,3924,3.8,1.0,2328,0,0,69,92,117,218,0,0
99998,99999,72,Female,27.8,16110,5.6,0.8,3093,0,0,93,164,72,188,0,0
99999,100000,37,Male,35.4,8222,9.1,1.8,3942,0,1,71,145,80,276,0,1

--------------------------------------------------------------------------

## ○ Especificar el tipo de datos de cada columna

In [10]:
data.dtypes # asi sera mas sencillo ver el Data type

id                     int64
age                    int64
gender                object
bmi                  float64
daily_steps            int64
sleep_hours          float64
water_intake_l       float64
calories_consumed      int64
smoker                 int64
alcohol                int64
resting_hr             int64
systolic_bp            int64
diastolic_bp           int64
cholesterol            int64
family_history         int64
disease_risk           int64
dtype: object

Entonces tenemos los siguientes tipos de datos (sin las abreviaturas) :





| **Columna**     | **Tipo de dato**      |
|--------------|---------------------------|
|**id**   |  Integer (64 bits) |
|**age**     |  Integer (64 bits)                  |
|**gender**    |     Object            |
|**bmi**| Float (64 bits)
|**daily_steps**        | Integer (64 bits)
|**sleep_hours**        | Float (64 bits)
|**water_intake_l**        | Float (64 bits)
|**calories_consumed**        |Integer (64 bits)
|**smoker**        |Integer (64 bits)
|**alcohol**        |Integer (64 bits)
|**resting_hr**        |Integer (64 bits)
|**systolic_bp**        |Integer (64 bits)
|**diastolic_bp**        |Integer (64 bits)
|**cholesterol**        |Integer (64 bits)
|**family_history**        |Integer (64 bits)
|**disease_risk**        |Integer (64 bits)

--------------------------------------------------------------------------

## ○ Si es necesario, asignar una columna como índice

Como observamos anteriormente, el dataset ya cuenta con una columna de id, la cual sigue un orden secuencial y podemos utilizarla como índice debido al formato secuencial y que es congrunte con el numero de registros que tenemos, por lo que no sera necesario asignar una columna nueva para el índice

--------------------------------------------------------------------------

## ○ Crear, modificar o eliminar columnas

In [35]:
#No veo necesario crear columnas nuevas debido a que la informacion necesaria ya se encuentra ahi
#Pero si veo necesario modificar la columna de Genero (gender)
#Esto para que tome valores binarios y no sea la unica columna del Dataframe con texto

data['gender_bin'] = data['gender'].map({'Male': 0, 'Female': 1})
#como me daba error al hacer la modificacion sobre gender, la hice en una columna nueva y luego la reemplaze con la nueva
data['gender'] = data['gender_bin']
data.drop('gender_bin', axis=1, inplace=True) #eliminamos la columna para no tener duplicadas
#ya se ve el cambio al hacer el display del dataframe
data

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
0,1,56,0,20.5,4198,3.9,3.4,1602,0,0,97,161,111,240,0,0
1,2,69,1,33.3,14359,9.0,4.7,2346,0,1,68,116,65,207,0,0
2,3,46,0,31.6,1817,6.6,4.2,1643,0,1,90,123,99,296,0,0
3,4,32,1,38.2,15772,3.6,2.0,2460,0,0,71,165,95,175,0,0
4,5,60,1,33.6,6037,3.8,4.0,3756,0,1,98,139,61,294,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,53,0,33.1,4726,3.9,2.0,3118,0,1,56,105,76,282,0,0
99996,99997,22,0,35.1,11554,4.5,3.1,1967,0,0,51,149,77,192,0,0
99997,99998,37,0,18.9,3924,3.8,1.0,2328,0,0,69,92,117,218,0,0
99998,99999,72,1,27.8,16110,5.6,0.8,3093,0,0,93,164,72,188,0,0
99999,100000,37,0,35.4,8222,9.1,1.8,3942,0,1,71,145,80,276,0,1

In [36]:

#Adicionalmente voy a verificar si no hay nulls o na, para ver si se les puede dar un tratamiento a aquellas columnas
#que los presenten
data.isnull().sum()

id                   0
age                  0
gender               0
bmi                  0
daily_steps          0
sleep_hours          0
water_intake_l       0
calories_consumed    0
smoker               0
alcohol              0
resting_hr           0
systolic_bp          0
diastolic_bp         0
cholesterol          0
family_history       0
disease_risk         0
dtype: int64

In [37]:
data.isna().sum()

id                   0
age                  0
gender               0
bmi                  0
daily_steps          0
sleep_hours          0
water_intake_l       0
calories_consumed    0
smoker               0
alcohol              0
resting_hr           0
systolic_bp          0
diastolic_bp         0
cholesterol          0
family_history       0
disease_risk         0
dtype: int64

Como observamos no hay 'null' ni 'na' en nuestras columnas, lo cual es un buen indicio de que no habra que limpiar las columnas por ese lado.

--------------------------------------------------------------------------

## ○ Filtrar registros

In [39]:
#Vamos a filtrar varias columnas para ver como se reflejan en el dataframe
data.query('smoker == 1 & alcohol == 1')
#obtenemos 6074 registros de personas que si fuman y si consumen alcohol
#teniendo un 6% de personas que consumen ambas sustancias en total de todo nuestro dataset

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
10,11,36,0,20.8,17215,4.2,5.0,2732,1,1,98,119,64,189,1,0
15,16,70,0,25.8,18483,5.6,1.4,2759,1,1,86,153,105,167,0,1
33,34,39,1,33.1,6215,8.2,1.2,1649,1,1,76,150,95,234,0,0
41,42,45,1,18.8,3531,3.4,2.5,1736,1,1,89,123,89,275,1,0
47,48,64,1,22.7,10193,3.1,1.7,3496,1,1,79,134,113,223,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99952,99953,38,0,31.3,10367,9.7,0.6,2099,1,1,53,123,91,273,0,0
99957,99958,70,1,32.3,14687,5.3,3.0,3333,1,1,76,175,86,170,1,1
99969,99970,74,1,22.7,3738,7.5,4.9,3919,1,1,88,147,85,212,0,0
99973,99974,59,0,35.1,18082,9.3,1.4,2376,1,1,77,127,81,166,0,1
99978,99979,52,1,34.1,2510,4.9,2.7,3653,1,1,96,128,62,298,1,0

In [40]:
data.query('daily_steps > 10000')
#Ahora obtenemos 52440 personas que realizan mas de 10 mil pasos diarios
#numero el cual diversos estudios indican, son los pasos necesarios para considerarse una persona activa

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
1,2,69,1,33.3,14359,9.0,4.7,2346,0,1,68,116,65,207,0,0
3,4,32,1,38.2,15772,3.6,2.0,2460,0,0,71,165,95,175,0,0
5,6,25,0,27.3,19495,5.0,4.4,1301,0,1,73,107,65,284,0,0
6,7,78,1,37.1,16739,9.5,4.2,3478,1,0,90,110,102,201,0,0
10,11,36,0,20.8,17215,4.2,5.0,2732,1,1,98,119,64,189,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99982,99983,22,1,36.1,17181,9.3,3.1,1433,0,1,90,163,110,205,0,0
99989,99990,24,1,35.4,12177,7.2,2.8,1495,0,0,66,169,90,242,0,1
99990,99991,53,0,26.0,16162,6.2,2.4,2374,0,0,94,154,65,271,0,1
99996,99997,22,0,35.1,11554,4.5,3.1,1967,0,0,51,149,77,192,0,0
99998,99999,72,1,27.8,16110,5.6,0.8,3093,0,0,93,164,72,188,0,0

--------------------------------------------------------------------------

## ○ Crear subconjutos de datos

In [41]:
#Vamos a crear 3 subconjuntos de datos
# 1. Aquellos Masculinos que duerman mas de 8 horas
data_male_sleep8 = data.query('gender == 0 & sleep_hours >= 8')
data_male_sleep8

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
19,20,20,0,35.7,1398,8.5,3.3,2161,0,0,57,167,100,272,1,0
22,23,19,0,35.7,19840,9.3,3.6,3365,0,0,92,177,78,187,0,0
26,27,55,0,32.6,15952,9.8,1.3,3762,0,0,62,105,97,204,0,0
32,33,75,0,23.2,15702,10.0,1.0,2695,0,0,64,125,106,252,0,0
53,54,74,0,36.9,19644,9.3,0.7,1418,0,1,98,105,74,262,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99971,99972,32,0,23.0,14229,9.9,3.2,1687,0,0,66,141,64,221,0,0
99973,99974,59,0,35.1,18082,9.3,1.4,2376,1,1,77,127,81,166,0,1
99985,99986,67,0,34.5,3207,8.0,4.2,2051,0,0,82,157,95,286,1,0
99991,99992,25,0,23.2,8493,8.8,3.7,1385,0,1,66,93,107,268,1,0
99999,100000,37,0,35.4,8222,9.1,1.8,3942,0,1,71,145,80,276,0,1

In [42]:
# 2. Aquellas personas con riesgo de enfermedad relacionado a su estilo de vida
data_with_disease = data.query('disease_risk == 1')
data_with_disease

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
15,16,70,0,25.8,18483,5.6,1.4,2759,1,1,86,153,105,167,0,1
17,18,57,1,29.9,2046,9.7,4.4,1506,0,0,84,136,68,188,0,1
21,22,70,0,28.4,19659,5.1,4.1,2814,0,1,66,125,107,224,0,1
29,30,38,1,34.6,9098,9.6,0.7,2531,0,0,92,140,73,180,0,1
36,37,42,1,34.2,3302,7.2,4.8,3990,0,0,65,91,117,252,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99979,99980,71,0,20.0,17603,7.7,4.0,3757,0,0,90,99,110,280,0,1
99984,99985,58,1,23.1,6532,6.0,4.9,1874,0,0,50,170,115,163,1,1
99989,99990,24,1,35.4,12177,7.2,2.8,1495,0,0,66,169,90,242,0,1
99990,99991,53,0,26.0,16162,6.2,2.4,2374,0,0,94,154,65,271,0,1
99999,100000,37,0,35.4,8222,9.1,1.8,3942,0,1,71,145,80,276,0,1

In [43]:
# 3. Aquellos Masculinos que tienen riesgo de enfermedad relacionado al estilo de vida
data_male_with_disease = data.query('gender == 0 & disease_risk == 1')
data_male_with_disease

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
15,16,70,0,25.8,18483,5.6,1.4,2759,1,1,86,153,105,167,0,1
21,22,70,0,28.4,19659,5.1,4.1,2814,0,1,66,125,107,224,0,1
60,61,56,0,29.3,11461,3.7,0.7,3505,0,1,94,143,67,256,1,1
79,80,25,0,30.5,15660,8.0,1.4,2354,0,0,92,159,91,189,0,1
87,88,21,0,37.5,5400,5.8,1.9,2205,0,0,57,124,74,230,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99973,99974,59,0,35.1,18082,9.3,1.4,2376,1,1,77,127,81,166,0,1
99977,99978,44,0,36.9,6572,6.4,4.5,2571,1,0,73,101,91,238,0,1
99979,99980,71,0,20.0,17603,7.7,4.0,3757,0,0,90,99,110,280,0,1
99990,99991,53,0,26.0,16162,6.2,2.4,2374,0,0,94,154,65,271,0,1
99999,100000,37,0,35.4,8222,9.1,1.8,3942,0,1,71,145,80,276,0,1

--------------------------------------------------------------------------

## ○ Crear grupos de datos

In [48]:
#Vamos a crear 2 Grupos de datos
#1. Vamos a agrupar por genero, el numero de personas que consumen alcohol
data.groupby('gender')['alcohol'].sum()
#obtenemos que los hombres, en este dataset son quienes mas consumen alcohol

gender
0    15147
1    14855
Name: alcohol, dtype: int64

In [50]:
#2. Vamos a agrupar por genero, habito de fumar y tambien de consumir alcohol, el promedio
# de la presion sistólica (en personas jovenes debe ser de 120 para considerarse presion 'sana')
data.groupby(['gender', 'smoker','alcohol'])['systolic_bp'].mean()
#el resultado no es tan alentador, vemos que no hay mucha diferencia en la media si se compara
#a una persona que consume ambas sustancias, con aquella que no.

gender  smoker  alcohol
0       0       0          134.716160
                1          134.337613
        1       0          135.085146
                1          134.260898
1       0       0          134.501217
                1          134.374272
        1       0          134.638226
                1          134.871000
Name: systolic_bp, dtype: float64